#!/bin/bash
# Create certificate via web interface with enhanced security

if [ $# -ne 4 ]; then
    echo "Usage: $0 <cert-name> <duration-days> <purpose> <password>"
    exit 1
fi

CERT_NAME=$1
DURATION_DAYS=$2
PURPOSE=$3
P12_PASSWORD=$4
CERT_DIR="certs/sales"

# Read CA password from file
CA_PASSWORD=$(cat certs/ca/.ca_password)

echo "🌐 Creating web-generated certificate: $CERT_NAME ($DURATION_DAYS days)"

# Generate private key
openssl genrsa -out "$CERT_DIR/${CERT_NAME}.key" 2048

# Create certificate signing request with web-generated marker
openssl req -new \
    -key "$CERT_DIR/${CERT_NAME}.key" \
    -out "$CERT_DIR/${CERT_NAME}.csr" \
    -subj "/C=US/ST=Louisiana/L=New Orleans/O=Mardi Gras World/OU=Web-Generated/CN=${CERT_NAME}.mardigrasworld.com"

# Sign the certificate with specified duration
openssl x509 -req -days $DURATION_DAYS \
    -in "$CERT_DIR/${CERT_NAME}.csr" \
    -CA certs/ca/mardi-gras-ca.crt \
    -CAkey certs/ca/mardi-gras-ca.key \
    -passin pass:$CA_PASSWORD \
    -out "$CERT_DIR/${CERT_NAME}.crt" \
    -extensions web_cert \
    -extfile <(echo "[web_cert]
keyUsage=digitalSignature,keyEncipherment
extendedKeyUsage=clientAuth
subjectAltName=DNS:${CERT_NAME}.mardigrasworld.com,DNS:${CERT_NAME},DNS:pixie-viewer.mardigrasworld.com,DNS:pixieview-demo.up.railway.app
basicConstraints=critical,CA:FALSE
# Mark as web-generated for identification
1.3.6.1.4.1.99999.1=ASN1:UTF8String:WebGenerated")

# Create PKCS#12 bundle with provided password
openssl pkcs12 -export \
    -in "$CERT_DIR/${CERT_NAME}.crt" \
    -inkey "$CERT_DIR/${CERT_NAME}.key" \
    -certfile certs/ca/mardi-gras-ca.crt \
    -out "$CERT_DIR/${CERT_NAME}.p12" \
    -name "Mardi Gras World - ${CERT_NAME} (${PURPOSE})" \
    -passout pass:$P12_PASSWORD

# Create installation instructions
cat > "$CERT_DIR/${CERT_NAME}-install.txt" << EOF
🌐 WEB-GENERATED CERTIFICATE: $CERT_NAME

Device: Current device
Purpose: $PURPOSE  
Valid for: $DURATION_DAYS days
Generated: $(date)

INSTALLATION:
1. Download the ${CERT_NAME}.p12 file
2. Double-click to install (desktop) or email to mobile device
3. Enter password when prompted: $P12_PASSWORD
4. Access Pixie Viewer at: https://pixie-viewer.mardigrasworld.com:3443 or https://pixieview-demo.up.railway.app

SECURITY NOTES:
- This is a short-term certificate for immediate access
- Certificate expires automatically in $DURATION_DAYS days
- Can be revoked immediately via admin interface
- All access is logged for security auditing

Generated by: Web Interface
Certificate Type: Web-Generated (Sales)
EOF

echo "✅ Web certificate created successfully!"
echo "📄 Certificate: $CERT_DIR/${CERT_NAME}.crt"
echo "📦 PKCS#12: $CERT_DIR/${CERT_NAME}.p12"
echo "🔐 Password: $P12_PASSWORD"
echo "⏰ Expires: $DURATION_DAYS days"